name: CD

on:
  release:
    types: [published]

jobs:

  setup:
    name: Setup environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r requirements.txt

      - run: gdown --fuzzy "$GOOGLE_DRIVE_LINK" -O dataset.tar
        env:
          GOOGLE_DRIVE_LINK: ${{ secrets.GOOGLE_DRIVE_LINK }}
