name: CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published]

permissions:
  checks: write
  packages: write

jobs:

  build-image:

    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.image-metadata.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set Docker image metadata
        id: image-metadata
        shell: bash
        env:
          GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          RUN_ID: ${{ github.run_id }}
          RUN_ATTEMPT: ${{ github.run_attempt }}
        run: |
          echo "tag=${GIT_SHA::7}-${RUN_ID}-${RUN_ATTEMPT}-dev" >> "$GITHUB_OUTPUT"

      - name: Build and push temporary Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          target: dev
          platforms: linux/amd64
          provenance: false
          cache-from: type=gha,scope=classification-model-dev
          cache-to: type=gha,mode=max,scope=classification-model-dev
          tags: ghcr.io/${{ github.repository_owner }}/${{ vars.IMAGE_NAME }}:${{ steps.image-metadata.outputs.tag }}
