name: CI

on:
  push:
  pull_request:

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - name: get repo
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: set up uv
        uses: astral-sh/setup-uv@v5

      - name: install dependencies
        run: |
          uv pip install --system flake8 "black[jupyter]" isort

      - name: lint with flake8
        run: |
          flake8

      - name: lint with black
        run: |
          black --check .

      - name: lint with isort
        run: |
          isort --check .

  test:

      runs-on: ubuntu-latest

      steps:

        - name: get repo
          uses: actions/checkout@v3

        - name: set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.12"

        - run: HEAVYEDGE_TEST_MODE=1 ./setup.sh
          env:
            HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
            LABELS_V1_GDRIVE: ${{ secrets.LABELS_V1_GDRIVE }}

        - name: build models
          run: HEAVYEDGE_TEST_MODE=1 make model models

        - name: test model
          run: HEAVYEDGE_TEST_MODE=1 make test

        - uses: actions/upload-artifact@v4
          with:
            name: train-data
            path: |
              _data/v1/profiles/dataset5/*
              _data/v1/labels/dataset5/*
            retention-days: 1

        - uses: actions/upload-artifact@v4
          with:
            name: trained-models
            path: |
              model/*
              models/*
            retention-days: 1

  image-infer:

      needs: test

      runs-on: ubuntu-latest

      steps:

        - name: Checkout
          uses: actions/checkout@v4

        - uses: actions/download-artifact@v4
          with:
            name: train-data
            path: _data/v1

        - uses: actions/download-artifact@v4
          with:
            name: trained-models
            path: .

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build Docker image
          uses: docker/build-push-action@v6
          with:
            context: .
            load: true
            push: false
            target: infer
            cache-from: type=gha,scope=classification-models-infer
            cache-to: type=gha,mode=max,scope=classification-models-infer
            tags: heavyedge-classification-models:infer-ci

        - name: Test Docker image
          run: |
            docker run --rm -w /workdir -v $PWD/_data/v1/profiles/dataset5:/workdir heavyedge-classification-models:infer-ci sh -c "uv pip install --system -r /app/model/requirements.txt && heavyedge classify-predict 001-Mean.h5 /app/model/model.pkl -o $(mktemp).csv"

  image-base:

      needs: test

      runs-on: ubuntu-latest

      steps:

        - name: Checkout
          uses: actions/checkout@v4

        - uses: actions/download-artifact@v4
          with:
            name: train-data
            path: _data/v1

        - uses: actions/download-artifact@v4
          with:
            name: trained-models
            path: .

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build Docker image
          uses: docker/build-push-action@v6
          with:
            context: .
            load: true
            push: false
            target: base
            cache-from: type=gha,scope=classification-models-base
            cache-to: type=gha,mode=max,scope=classification-models-base
            tags: heavyedge-classification-models:base-ci

        - name: Test Docker image
          run: |
            docker run --rm -w /workdir -v $PWD/_data/v1/profiles/dataset5:/workdir heavyedge-classification-models:base-ci sh -c "uv pip install --system -r /app/model/requirements.txt && heavyedge classify-predict 001-Mean.h5 /app/model/model.pkl -o $(mktemp).csv"
            docker run --rm -v $PWD/_data:/app/_data heavyedge-classification-models:base-ci sh -c 'uv pip install --system -r requirements.txt && HEAVYEDGE_TEST_MODE=1 make all test'

  image-dev:

      needs: test

      runs-on: ubuntu-latest

      steps:

        - name: Checkout
          uses: actions/checkout@v4

        - uses: actions/download-artifact@v4
          with:
            name: train-data
            path: _data/v1

        - uses: actions/download-artifact@v4
          with:
            name: trained-models
            path: .

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build Docker image
          uses: docker/build-push-action@v6
          with:
            context: .
            load: true
            push: false
            target: dev
            cache-from: type=gha,scope=classification-models-dev
            cache-to: type=gha,mode=max,scope=classification-models-dev
            tags: heavyedge-classification-models:dev-ci

        - name: Test Docker image
          run: |
            docker run --rm heavyedge-classification-models:dev-ci sh -c "uv pip install --system -r requirements.txt && heavyedge classify-predict _data/v1/profiles/dataset5/001-Mean.h5 ./model/model.pkl -o $(mktemp).csv"
            docker run --rm heavyedge-classification-models:dev-ci sh -c 'uv pip install --system -r requirements.txt && HEAVYEDGE_TEST_MODE=1 make all test'
