name: CI

on: [push, pull_request]

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - name: get repo
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: install dependencies
        run: |
          pip install flake8 black[jupyter] isort

      - name: lint with flake8
        run: |
          flake8

      - name: lint with black
        run: |
          black --check .

      - name: lint with isort
        run: |
          isort --check .

  train-models:

      needs: lint

      runs-on: ubuntu-latest

      steps:

        - name: get repo
          uses: actions/checkout@v3

        - name: set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.12"

        - run: ./setup.sh
          env:
            HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
            LABELS_V1_GDRIVE: ${{ secrets.LABELS_V1_GDRIVE }}

        - name: build model
          run: make
